nelmio_cors:
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['Origin','Accept','Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ['Location', 'Retry-After', 'ETag']
            max_age: 3600
