<?php

namespace App\TPChallengeBundle\Repository;

use Doctrine\ORM\Query;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $nickname
     * @return int|mixed|string
     */
    public function findPlayerGamesByNickname($nickname)
    {
        return $this
            ->getPlayerByNicknameQueryBuilder($nickname)
            ->orderBy('s.createdAt','DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    protected function getPlayerByNicknameQueryBuilder(string $nickname)
    {
        return $this->createQueryBuilder('s')
            ->andWhere('s.nickName = :nickname')
            ->setParameter('nickname', $nickname)
        ;
    }
}
