#index:
#    path: /
#    controller: App\Controller\DefaultController::index
tp_challenge:
  resource: '@TPChallengeBundle/Controller/'
  type: annotation
  prefix: /api

tp_challenge_html:
  resource: '@TPChallengeBundle/Controller/HtmlController.php'
  type: annotation
